### ISSUE TITLE
TPP coordinates begin at 1,1 rather than 0,0

### ISSUE THREAD

**Issue by schas002** [hftf/coords#27]
According to [TPP's profile](http://www.twitch.tv/twitchplayspokemon/profile), 

> the range is 1,1~256,192 with 1,1 being the top left pixel of the touch screen

instead of 0,0~255,191 where 0,0 is the top left pixel of the touch screen.

**Comment by MattiasBuelens** [comment]
This is a known problem with the way the streamer has set up the touch screen inputs.

The stream accepts touch commands in the range `1,1` to `256,192`, but the emulator accepts inputs in the range `0,0` to `255,191`. **The stream does not account for this difference!** Therefore, the 256th row and the 192th column don't actually do anything (because the emulator doesn't accept it), and we cannot hit the 0th row or column (because the stream doesn't accept it).

In practice, this means that you can only use `1,1` to `255,191` as coordinates. Other than that, the coordinates used by the tool are correct: the stream doesn't do the coordinate shift, so we don't need to adjust for that.
