### ISSUE TITLE
Suggested ordering and info about Black 2 Fly screen

### ISSUE THREAD

**Issue by DrClipper** [hftf/coords#30]
The following order matches the order you visit the towns in Black 2 (except for the post game ones).  Might be the least confusing:
Main Game:
        Aspertia
        Flocessy
        Virbank
        Pokéstar Studios
        Castelia
        Join Avenue
        Nimbasa
        Driftveil
        Pokémon World Tournament
        Mistralton
        Lentimas
        Undella
        Lacunosa
        Opelucid
        Humilau
        Victory Road
        Pokemon League
Post Game:
        Nuvema
        Accumula
        Striaton
        Nacrene
        Icirrus
        Black City

Also, I noticed that Join Avenue has a rather odd, non-rectangular hit-box, as it's covered by other hitboxes from the nearby routes. In particular, note that 125,100 and 125,107 hit Join Avenue, but some of the intervening pixels do not.  This same issue might also exist for other Fly locations...

**Comment by MattiasBuelens** [comment]
That ordering makes much more sense indeed, it's in 1f3759f40031f89de8909354a0664da0ffd9307f now.

It seems like Desert Resort overlaps both Relic Castle and Join Avenue. More precisely, Desert Resort is from `117,100` to `129,106` whereas Join Avenue is from `123,99` to `139,107`. This Join Avenue hitbox would actually make sense, since this brings it back to a 16 by 8 area just like all the other fly locations.

The overlap region is `123,100` to `129,106`, in which Desert Resort is overlapped _above_ Join Avenue. Join Avenue can thus only be hit from `123,99` to `139,99`, `130,100` to `139,106` and `123,107` to `139,107`. So it looks like we'll need to divide Join Avenue into three sections... _\_sigh**

**Comment by hftf** [comment]
I'm glad I'm not the one figuring out the rectangles — er, I mean geometric shapes — anymore :relieved:

**Comment by MattiasBuelens** [comment]
And another hit: Victory Road actually is from `175,11` to `191,19`, but the Pokémon League overlaps from `175,11` to `177,18`. Thus Victory Road can only be hit from `175,19` to `177,19` and `178,11` to `191,19`. :stuck_out_tongue:

**Comment by MattiasBuelens** [comment]
Okay, fix is up on 1f3759f40031f89de8909354a0664da0ffd9307f. Expect a pull request soon.

Side note: I simply gave these extra regions numerical IDs for now: e.g. `F`, `1` and `2`. I'd rather give them IDs such as `F`, `F2` and `F3` to keep these related to the "main" fly location box. It _seems_ like the tool handles longer IDs just fine, but I'd like to have some confirmation if this can be relied on in the future.

So @hftf, should we use longer IDs for buttons or not? This would also make sense for things like Options, e.g. `Sf` for "Speed Fast". Downside would be that longer IDs will break the neat vertical alignment of the `{id, coords}` objects...

**Comment by hftf** [comment]
The IDs are so arbitrary as is that I question whether it's worth the effort (at least in this iteration of the site). I'm gonna say "no, but I'll let you choose" unless you convince me with a compelling reason to have "proper" IDs.
